'use client';

import { Clock3, FileText, Loader2, Sparkles } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import { formatRelativeTime } from '@/lib/format';

interface AISummaryCardProps {
  title: string;
  summary?: string | null;
  generatedAt?: string | null;
  status?: 'Pending' | 'Generated' | 'Failed' | null;
  className?: string;
}

export function AISummaryCard({
  title,
  summary,
  generatedAt,
  status,
  className,
}: AISummaryCardProps) {
  const hasSummary = Boolean(summary);
  const generatedLabel = generatedAt
    ? formatRelativeTime(new Date(generatedAt))
    : null;
  const isSyncing = status === 'Pending' && !hasSummary;

  return (
    <div
      className={cn(
        'rounded-xl border border-clinch-border-default bg-clinch-bg-card p-6',
        className,
      )}
    >
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex items-start gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-clinch-border-default bg-clinch-bg-elevated">
            {isSyncing ? (
              <Loader2 className="h-4 w-4 animate-spin text-clinch-accent" />
            ) : hasSummary ? (
              <Sparkles className="h-4 w-4 text-clinch-accent" />
            ) : (
              <FileText className="h-4 w-4 text-clinch-text-tertiary" />
            )}
          </div>
          <div>
            <h3 className="text-h4 text-clinch-text-primary">{title}</h3>
            <p className="mt-1 text-xs leading-5 text-clinch-text-tertiary">
              Generated by AI. Cached result for this agreement.
            </p>
          </div>
        </div>

        <div className="flex flex-wrap gap-2">
          <Badge className="border border-clinch-border-default bg-clinch-bg-elevated text-clinch-text-secondary">
            Generated by AI
          </Badge>
          {hasSummary && (
            <Badge className="border border-clinch-success/20 bg-clinch-success-muted text-clinch-success">
              Cached result
            </Badge>
          )}
          {!hasSummary && (
            <Badge className="border border-clinch-warning/20 bg-clinch-warning-muted text-clinch-warning">
              {isSyncing ? 'Syncing' : 'Pending'}
            </Badge>
          )}
        </div>
      </div>

      {hasSummary ? (
        <div className="mt-5 rounded-lg border border-clinch-border-default bg-clinch-bg-page/60 p-4">
          <p className="text-sm leading-6 text-clinch-text-primary">
            {summary}
          </p>
        </div>
      ) : (
        <div className="mt-5 rounded-lg border border-dashed border-clinch-border-default bg-clinch-bg-page/60 p-4">
          <div className="flex items-start gap-3">
            <Clock3 className="mt-0.5 h-4 w-4 text-clinch-accent" />
            <p className="text-sm leading-6 text-clinch-text-secondary">
              Clinch is preparing the indexed report. The page remains usable while the cached result syncs.
            </p>
          </div>
        </div>
      )}

      <div className="mt-4 flex flex-col gap-2 border-t border-clinch-border-default pt-3 text-xs leading-5 text-clinch-text-tertiary sm:flex-row sm:items-center sm:justify-between">
        <span>
          AI output is informational and based only on indexed escrow records.
        </span>
        {generatedLabel && <span>Updated {generatedLabel}</span>}
      </div>
    </div>
  );
}
